import remote.IRemoteBoard;

import javax.swing.*;
import javax.swing.border.BevelBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.rmi.RemoteException;

public class Canvas extends JFrame {
    private String mode;
    private Point start;
    private Point end;
    private Point remoteStart;
    private Point remoteEnd;
    private String remoteMode;
    private IRemoteBoard remoteBoard;
    public final String DRAWLINE = "drawLine";
    public final String FREEDRAW = "freeDraw";
    public final String DRAWREC = "drawRec";
    public final String DRAWCIRCLE = "drawCircle";
    public final String DRAWTRI = "drawTri";
    public final String DRAWTEXT = "drawText";
    public final String NOTHING = "";
    private String name;
    private Color color;
    private Color remoteColor;
    DefaultListModel chatModel;
    Graphics g;
    private boolean isManager;
    private String fileName;
    private BufferedImage image;
    private String textDraw;
    private String remoteTextDraw;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel boardPanel;
    private JScrollPane chatBoxPanel;
    private JLabel chatLabel;
    private JList<String> chatList;
    private JPanel chatPanel;
    private JButton clearButton;
    private JMenuItem colorChooser;
    private JMenu colorMenu;
    private JMenu currentColor;
    private JMenu currentTool;
    private JRadioButtonMenuItem cursorButton;
    private JMenu cursorMenu;
    private JRadioButtonMenuItem drawCir;
    private JLabel drawLabel;
    private JRadioButtonMenuItem drawLine;
    private JRadioButtonMenuItem drawRect;
    private JRadioButtonMenuItem drawText;
    private JRadioButtonMenuItem drawTri;
    private JMenuItem fileClose;
    private JMenu fileMenu;
    private JMenuItem fileOpen;
    private JMenuItem fileSave;
    private JMenuItem fileSaveAs;
    private JMenu freeDraw;
    private JRadioButtonMenuItem freeDrawButton;
    private JTextArea inputArea;
    private JScrollPane inputPanel;
    private JPanel listPanel;
    private JMenuBar menuBar;
    private ButtonGroup modeGroup;
    private JMenuItem newBoard;
    private JButton sendButton;
    private JMenu shapeMenu;
    private JMenu textMenu;
    private JList<String> userList;
    private JLabel userListLabel;
    private JScrollPane userListPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form BoardClient
     */
    public Canvas(){
        super.setTitle("ZX Share White Board ~_~");
//        mode = "";
//        remoteStart = new Point(0, 0);
//        remoteEnd = new Point(0, 0);
//        start = new Point(0, 0);
//        end = new Point(0, 0);
//        this.name = name;
//        userList = new JList<>();
//        color = new Color(0, 0, 0);
//        remoteColor = new Color(0, 0, 0);
//        chatModel = new DefaultListModel();
        initComponents();
//        fileName = null;
//        image  = new BufferedImage(boardPanel.getWidth(), boardPanel.getHeight(), BufferedImage.TYPE_INT_RGB);
//        g = image.createGraphics();
//        g.setColor(Color.white);
//        g.fillRect(0, 0, boardPanel.getWidth(), boardPanel.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeGroup = new ButtonGroup();
        boardPanel = new JPanel();
        drawLabel = new JLabel();
        inputPanel = new JScrollPane();
        inputArea = new JTextArea();
        sendButton = new JButton();
        clearButton = new JButton();
        listPanel = new JPanel();
        userListLabel = new JLabel();
        userListPanel = new JScrollPane();
        userList = new JList<>();
        chatPanel = new JPanel();
        chatLabel = new JLabel();
        chatBoxPanel = new JScrollPane();
        chatList = new JList<>();
        menuBar = new JMenuBar();
        fileMenu = new JMenu();
        newBoard = new JMenuItem();
        fileOpen = new JMenuItem();
        fileSave = new JMenuItem();
        fileSaveAs = new JMenuItem();
        fileClose = new JMenuItem();
        shapeMenu = new JMenu();
        drawLine = new JRadioButtonMenuItem();
        drawRect = new JRadioButtonMenuItem();
        drawTri = new JRadioButtonMenuItem();
        drawCir = new JRadioButtonMenuItem();
        colorMenu = new JMenu();
        colorChooser = new JMenuItem();
        textMenu = new JMenu();
        drawText = new JRadioButtonMenuItem();
        freeDraw = new JMenu();
        freeDrawButton = new JRadioButtonMenuItem();
        cursorMenu = new JMenu();
        cursorButton = new JRadioButtonMenuItem();
        currentTool = new JMenu();
        currentColor = new JMenu();

        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        boardPanel.setBackground(new Color(255, 255, 255));
        boardPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                boardPanelMouseDragged(evt);
            }
        });
        boardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boardPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boardPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boardPanelMouseReleased(evt);
            }
        });
        boardPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                boardPanelKeyTyped(evt);
            }
        });

        drawLabel.setHorizontalAlignment(SwingConstants.CENTER);
        drawLabel.setText("Drawing Section");

        GroupLayout boardPanelLayout = new GroupLayout(boardPanel);
        boardPanel.setLayout(boardPanelLayout);
        boardPanelLayout.setHorizontalGroup(
                boardPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(boardPanelLayout.createSequentialGroup()
                                .addComponent(drawLabel)
                                .addGap(0, 339, Short.MAX_VALUE))
        );
        boardPanelLayout.setVerticalGroup(
                boardPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(boardPanelLayout.createSequentialGroup()
                                .addComponent(drawLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        inputPanel.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        inputPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

        inputArea.setColumns(20);
        inputArea.setLineWrap(true);
        inputArea.setRows(5);
        inputArea.setText("");
        inputPanel.setViewportView(inputArea);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        userListLabel.setHorizontalAlignment(SwingConstants.CENTER);
        userListLabel.setText("Participants");
        userListLabel.setHorizontalTextPosition(SwingConstants.CENTER);

        userList.setModel(new AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        userList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userListMouseClicked(evt);
            }
        });
        userListPanel.setViewportView(userList);

        GroupLayout listPanelLayout = new GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
                listPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(userListPanel)
                        .addGroup(listPanelLayout.createSequentialGroup()
                                .addComponent(userListLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        listPanelLayout.setVerticalGroup(
                listPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(listPanelLayout.createSequentialGroup()
                                .addComponent(userListLabel)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userListPanel, GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                .addContainerGap())
        );

        chatLabel.setHorizontalAlignment(SwingConstants.CENTER);
        chatLabel.setText("Chat");
        chatLabel.setHorizontalTextPosition(SwingConstants.CENTER);

        chatList.setModel(new AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        chatBoxPanel.setViewportView(chatList);

        GroupLayout chatPanelLayout = new GroupLayout(chatPanel);
        chatPanel.setLayout(chatPanelLayout);
        chatPanelLayout.setHorizontalGroup(
                chatPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(chatBoxPanel)
                        .addGroup(chatPanelLayout.createSequentialGroup()
                                .addComponent(chatLabel)
                                .addGap(0, 147, Short.MAX_VALUE))
        );
        chatPanelLayout.setVerticalGroup(
                chatPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(chatPanelLayout.createSequentialGroup()
                                .addComponent(chatLabel)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chatBoxPanel, GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addContainerGap())
        );

        menuBar.setMaximumSize(new Dimension(200, 30));
        menuBar.setMinimumSize(new Dimension(20, 20));
        menuBar.setPreferredSize(new Dimension(300, 27));

        if (!isManager) {
            fileMenu.setVisible(false);
        }

        fileMenu.setText("File");

        newBoard.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
//        newBoard.setIcon(new ImageIcon(getClass().getResource("/icon/newboard.png"))); // NOI18N
        newBoard.setText("New Board");
        newBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBoardActionPerformed(evt);
            }
        });
        fileMenu.add(newBoard);

        fileOpen.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
//        fileOpen.setIcon(new ImageIcon(getClass().getResource("/icon/openfile.png"))); // NOI18N
        fileOpen.setText("Open");
        fileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileOpenActionPerformed(evt);
            }
        });
        fileMenu.add(fileOpen);

        fileSave.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
//        fileSave.setIcon(new ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
        fileSave.setText("Save");
        fileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    fileSaveActionPerformed(evt);
                }catch (NullPointerException e){

                }
            }
        });
        fileMenu.add(fileSave);

        fileSaveAs.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
//        fileSaveAs.setIcon(new ImageIcon(getClass().getResource("/icon/saveas.png"))); // NOI18N
        fileSaveAs.setText("Save As");
        fileSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try{
                    fileSaveAsActionPerformed(evt);
                }catch (NullPointerException e){
                }
            }
        });
        fileMenu.add(fileSaveAs);

        fileClose.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
//        fileClose.setIcon(new ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        fileClose.setText("Close Board");
        fileClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileCloseActionPerformed(evt);
            }
        });
        fileMenu.add(fileClose);

        menuBar.add(fileMenu);

//        shapeMenu.setIcon(new ImageIcon(getClass().getResource("/icon/shape.png"))); // NOI18N
        shapeMenu.setText("Shape");
        shapeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shapeMenuMouseClicked(evt);
            }
        });

        drawLine.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        modeGroup.add(drawLine);
        drawLine.setText("Line");
//        drawLine.setIcon(new ImageIcon(getClass().getResource("/icon/line.png"))); // NOI18N
        drawLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawLineActionPerformed(evt);
            }
        });
        shapeMenu.add(drawLine);

        drawRect.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        modeGroup.add(drawRect);
        drawRect.setText("Rectangle");
//        drawRect.setIcon(new ImageIcon(getClass().getResource("/icon/rectangle.png"))); // NOI18N
        drawRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawRectActionPerformed(evt);
            }
        });
        shapeMenu.add(drawRect);

        drawTri.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        modeGroup.add(drawTri);
        drawTri.setText("Triangle");
//        drawTri.setIcon(new ImageIcon(getClass().getResource("/icon/triangle.png"))); // NOI18N
        drawTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawTriActionPerformed(evt);
            }
        });
        shapeMenu.add(drawTri);

        drawCir.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        modeGroup.add(drawCir);
        drawCir.setText("Circle");
//        drawCir.setIcon(new ImageIcon(getClass().getResource("/icon/circle.png"))); // NOI18N
        drawCir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawCirActionPerformed(evt);
            }
        });
        shapeMenu.add(drawCir);

        menuBar.add(shapeMenu);

//        colorMenu.setIcon(new ImageIcon(getClass().getResource("/icon/color.png"))); // NOI18N
        colorMenu.setText("Color");

//        colorChooser.setIcon(new ImageIcon(getClass().getResource("/icon/choosecolor.png"))); // NOI18N
        colorChooser.setText("Choose");
        colorChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorChooserActionPerformed(evt);
            }
        });
        colorMenu.add(colorChooser);

        menuBar.add(colorMenu);

//        textMenu.setIcon(new ImageIcon(getClass().getResource("/icon/text.png"))); // NOI18N
        textMenu.setText("Text");

        modeGroup.add(drawText);
        drawText.setSelected(false);
//        drawText.setIcon(new ImageIcon(getClass().getResource("/icon/drawtext.png"))); // NOI18N
        drawText.setSelected(true);
        drawText.setText("drawText");
        drawText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawTextActionPerformed(evt);
            }
        });
        textMenu.add(drawText);

        menuBar.add(textMenu);

//        freeDraw.setIcon(new ImageIcon(getClass().getResource("/icon/drawing.png"))); // NOI18N
        freeDraw.setText("Drawing");

        modeGroup.add(freeDrawButton);
        freeDrawButton.setText("Free Draw");
//        freeDrawButton.setIcon(new ImageIcon(getClass().getResource("/icon/freedraw.png"))); // NOI18N
        freeDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freeDrawButtonActionPerformed(evt);
            }
        });
        freeDraw.add(freeDrawButton);

        menuBar.add(freeDraw);

//        cursorMenu.setIcon(new ImageIcon(getClass().getResource("/icon/cursor.png"))); // NOI18N
        cursorMenu.setText("Cursor");

        modeGroup.add(cursorButton);
        cursorButton.setText("Mouse");
//        cursorButton.setIcon(new ImageIcon(getClass().getResource("/icon/cursor.png"))); // NOI18N
        cursorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursorButtonActionPerformed(evt);
            }
        });
        cursorMenu.add(cursorButton);

        menuBar.add(cursorMenu);

        currentTool.setBackground(Color.lightGray);
        currentTool.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        currentTool.setText("current tool");
        currentTool.setOpaque(true);
        currentTool.setIcon(cursorMenu.getIcon());
        // let the current tool be the left most icon
        JPanel panel = new JPanel();
        panel.add(Box.createHorizontalGlue());
        panel.add(currentTool);
        menuBar.add(Box.createHorizontalGlue());
        menuBar.add(panel);
        menuBar.add(currentTool);



        currentColor.setBackground(Color.lightGray);
        currentColor.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        currentColor.setText("current color");
        currentColor.setOpaque(true);
        menuBar.add(currentColor);

        setJMenuBar(menuBar);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(boardPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(sendButton)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(clearButton)
                                                .addGap(27, 27, 27))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(inputPanel, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(listPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(chatPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(4, 4, 4))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(boardPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(listPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chatPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(inputPanel)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(sendButton)
                                        .addComponent(clearButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boardPanelKeyTyped(KeyEvent evt) {
    }

    private void sendButtonActionPerformed(ActionEvent evt) {

    }

    private void clearButtonActionPerformed(ActionEvent evt) {

    }

    private void userListMouseClicked(MouseEvent evt) {

    }

    private void fileSaveActionPerformed(ActionEvent evt) {

    }

    private void fileCloseActionPerformed(ActionEvent evt) {

    }

    private void fileSaveAsActionPerformed(ActionEvent evt) {

    }

    private void shapeMenuMouseClicked(MouseEvent evt) {

    }

    private void drawTriActionPerformed(ActionEvent evt) {

    }

    private void drawLineActionPerformed(ActionEvent evt) {

    }

    private void drawRectActionPerformed(ActionEvent evt) {
        
    }

    private void drawCirActionPerformed(ActionEvent evt) {
        
    }

    private void colorChooserActionPerformed(ActionEvent evt) {
        
    }

    private void cursorButtonActionPerformed(ActionEvent evt) {
        
    }

    private void drawTextActionPerformed(ActionEvent evt) {
        
    }

    private void freeDrawButtonActionPerformed(ActionEvent evt) {
        
    }

    private void fileOpenActionPerformed(ActionEvent evt) {
        
    }

    private void newBoardActionPerformed(ActionEvent evt) {
        
    }

    private void boardPanelMouseReleased(MouseEvent evt) {
        
    }

    private void boardPanelMousePressed(MouseEvent evt) {
        
    }

    private void boardPanelMouseClicked(MouseEvent evt) {
        
    }

    private void boardPanelMouseDragged(MouseEvent evt) {
        
    }

    private void formWindowClosing(WindowEvent evt) {
    }

}
